"use client";
import "../lab.css";

import { useEffect, useRef, useState } from "react";
import type { MultiplayerSession } from "./room";

type Army = "Light" | "Medium" | "Heavy" | "Lab";
type Resource = "Steel" | "Energy" | "Intelligence" | "Alien Tech";
type Point = [number, number];
type Cell = { id: string; city: number; number: number; points: Point[]; center: Point };
type Unit = { id: string; army: Army; city: number; tile: number; alive: boolean };
type Card = { id: number; city: number; aliens: number; resources: Partial<Record<Resource, number>>; reinforcement: boolean };
type PendingAttack = { unitId: string; targets: string[]; remaining: number };
type Moment = { label:string; positions:string; state:{labCity:number;deck:Card[];index:number;card:Card|null;phase:"draw"|"collect"|"actions";turn:number;aliens:string[];units:Unit[];cursors:Record<number,number>;selected:string|null;moved:Record<string,number>;labMoved:boolean;reviveSpent:number;weapon:number;over:string|null;levels:Record<Army,number>;hands:Record<Army,Record<Resource,number>>;logs:string[];pendingAttack:PendingAttack|null} };

const ARMIES: Army[] = ["Light", "Medium", "Heavy", "Lab"];
const RESOURCES: Resource[] = ["Steel", "Energy", "Intelligence", "Alien Tech"];
const COLORS = ["#65b9cc", "#cf9f55", "#ae83cf", "#d66f69", "#77aa73"];
const MOVE: Record<Army, number> = { Light: 3, Medium: 2, Heavy: 1, Lab: 1 };
const KILLS: Record<Army, number> = { Light: 1, Medium: 2, Heavy: 3, Lab: 0 };
const CITY_RING = [1,2,3,5,4];
const NUMBERS = [1,2,5,6,9,10,13,14,3,4,7,8,11,12,15];
const COSTS: Record<Army, Array<Partial<Record<Resource, number>>>> = {
  Light: [{Steel:10,Energy:5},{Steel:5,Energy:15,Intelligence:5},{Steel:5,Energy:20,Intelligence:10}],
  Medium: [{Steel:5,Intelligence:10},{Steel:10,Energy:5,Intelligence:10},{Steel:10,Energy:15,Intelligence:10}],
  Heavy: [{Steel:10,Intelligence:5},{Steel:15,Energy:5,Intelligence:5},{Steel:25,Energy:5,Intelligence:5}],
  Lab: [{Energy:5,Intelligence:10},{Energy:10,Intelligence:15},{Steel:5,Energy:10,Intelligence:20}],
};
const POWERS: Record<Army,string[]> = {
  Light:["Move the Lab","Move Medium units","Move Heavy units"],
  Medium:["Drones kill 1","Drones kill 2","Drones kill 3"],
  Heavy:["Heavy drop armour","Medium drop armour","Light drop armour"],
  Lab:["Revive 2 points per turn","Revive 4 points per turn","Revive 6 points per turn"],
};
const TILES: Point[][] = [
 [[100,0],[20,0],[-11.177,54],[20,108],[100,108]],[[100,0],[180,0],[211.177,54],[180,108],[100,108]],
 [[100,108],[20,108],[-11.177,162],[20,216],[100,216]],[[100,108],[180,108],[211.177,162],[180,216],[100,216]],
 [[100,216],[20,216],[-11.177,270],[20,324],[100,324]],[[100,216],[180,216],[211.177,270],[180,324],[100,324]],
 [[100,324],[20,324],[-11.177,378],[20,432],[100,432]],[[100,324],[180,324],[211.177,378],[180,432],[100,432]],
 [[291.177,54],[211.177,54],[180,108],[211.177,162],[291.177,162]],[[291.177,54],[371.177,54],[402.354,108],[371.177,162],[291.177,162]],
 [[291.177,162],[211.177,162],[180,216],[211.177,270],[291.177,270]],[[291.177,162],[371.177,162],[402.354,216],[371.177,270],[291.177,270]],
 [[291.177,270],[211.177,270],[180,324],[211.177,378],[291.177,378]],[[291.177,270],[371.177,270],[402.354,324],[371.177,378],[291.177,378]],
 [[291.177,378],[211.177,378],[180,432],[211.177,486],[291.177,486]],
];
const LAYOUTS = [{x:0,y:0,r:false},{x:382.354,y:0,r:false},{x:764.708,y:0,r:false},{x:191.177,y:378,r:true},{x:573.531,y:378,r:true}];

function transform(p:Point,l:(typeof LAYOUTS)[number]):Point { return l.r?[390-p[0]+l.x,486-p[1]+l.y]:[p[0]+l.x,p[1]+l.y] }
function center(points:Point[]):Point { return [points.reduce((s,p)=>s+p[0],0)/5,points.reduce((s,p)=>s+p[1],0)/5] }
function cells():Cell[]{return LAYOUTS.flatMap((l,ci)=>TILES.map((t,ti)=>{const points=t.map(p=>transform(p,l));return{id:`${ci+1}-${NUMBERS[ti]}`,city:ci+1,number:NUMBERS[ti],points,center:center(points)}}))}
function edge(a:Point,b:Point){const x=`${a[0].toFixed(2)},${a[1].toFixed(2)}`,y=`${b[0].toFixed(2)},${b[1].toFixed(2)}`;return x<y?`${x}|${y}`:`${y}|${x}`}
function graph(cs:Cell[]){const edges=new Map<string,string[]>(),g=new Map<string,Set<string>>();cs.forEach(c=>{g.set(c.id,new Set());c.points.forEach((p,i)=>{const k=edge(p,c.points[(i+1)%5]);edges.set(k,[...(edges.get(k)||[]),c.id])})});edges.forEach(ids=>{if(ids.length===2){g.get(ids[0])!.add(ids[1]);g.get(ids[1])!.add(ids[0])}});const interRow=new Set(["1-4","2-4","2-5","3-5"]);for(let i=0;i<cs.length;i++)for(let j=i+1;j<cs.length;j++){const a=cs[i],b=cs[j],pair=[a.city,b.city].sort((x,y)=>x-y).join("-");if(!interRow.has(pair))continue;const distance=Math.hypot(a.center[0]-b.center[0],a.center[1]-b.center[1]);if(distance<=110){g.get(a.id)!.add(b.id);g.get(b.id)!.add(a.id)}}return g}
function empty(){return{Steel:0,Energy:0,Intelligence:0,"Alien Tech":0} as Record<Resource,number>}
function shuffle<T>(items:T[]):T[]{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function makeDeck():Card[]{
 const cycles:Resource[][]=[["Energy","Intelligence","Steel"],["Steel","Energy","Intelligence"],["Intelligence","Steel","Energy"],["Energy","Steel","Intelligence"],["Steel","Intelligence","Energy"],["Intelligence","Energy","Steel"]];
 const all=Array.from({length:60},(_,i)=>{const within=i%15,rs=cycles[i%6],tech=[3,8,13].includes(within);return{id:i+1,city:((i*2+Math.floor(i/15))%5)+1,aliens:[4,5,5,6,5,5][i%6],resources:tech?{[rs[0]]:3,[rs[1]]:2,"Alien Tech":1}:{[rs[0]]:3,[rs[1]]:2,[rs[2]]:1},reinforcement:within===8}});
 return [0,1,2,3].flatMap(s=>shuffle(all.slice(s*15,s*15+15)));
}
function initialUnits(city:number):Unit[]{const list:Army[]=["Heavy","Medium","Medium","Light","Light","Light"];return list.map((army,i)=>({id:`${army}-${i}`,army,city,tile:15-i,alive:true}))}
function costText(c:Partial<Record<Resource,number>>){return Object.entries(c).map(([r,n])=>`${n} ${r}`).join(" · ")}
const BOARD = cells();
const ADJACENCY = graph(BOARD);

export default function Home({multiplayer}:{multiplayer?:MultiplayerSession}){
 const board=BOARD,adj=ADJACENCY;
 const [labCity,setLabCity]=useState(1),[started,setStarted]=useState(false),[deck,setDeck]=useState<Card[]>([]),[index,setIndex]=useState(0),[card,setCard]=useState<Card|null>(null);
 const [phase,setPhase]=useState<"draw"|"collect"|"actions">("draw"),[turn,setTurn]=useState(0),[aliens,setAliens]=useState<Set<string>>(new Set()),[units,setUnits]=useState<Unit[]>([]);
 const [cursors,setCursors]=useState<Record<number,number>>({1:1,2:1,3:1,4:1,5:1});
 const [selected,setSelected]=useState<string|null>(null),[moved,setMoved]=useState<Record<string,number>>({}),[labMoved,setLabMoved]=useState(false),[reviveSpent,setReviveSpent]=useState(0),[weapon,setWeapon]=useState(0),[over,setOver]=useState<string|null>(null);
 const [pendingAttack,setPendingAttack]=useState<PendingAttack|null>(null);
 const [levels,setLevels]=useState<Record<Army,number>>({Light:0,Medium:0,Heavy:0,Lab:0});
 const [hands,setHands]=useState<Record<Army,Record<Resource,number>>>({Light:empty(),Medium:empty(),Heavy:empty(),Lab:empty()});
 const [history,setHistory]=useState<Moment[]>([]);
 const [logs,setLogs]=useState<string[]>(["Choose a landing city."]); const active=ARMIES[turn];
 const applyingRemote=useRef(false),lastRevision=useRef(-1),sendStateRef=useRef(multiplayer?.sendState);
 useEffect(()=>{sendStateRef.current=multiplayer?.sendState},[multiplayer?.sendState]);
 const canAct=!multiplayer||multiplayer.armies.includes(active)||!started;
 useEffect(()=>{const incoming=multiplayer?.view.gameState as (Moment["state"]&{started:boolean;history:Moment[]})|null|undefined,revision=multiplayer?.view.revision??-1;if(!incoming||revision<=lastRevision.current)return;lastRevision.current=revision;applyingRemote.current=true;setStarted(incoming.started);setLabCity(incoming.labCity);setDeck(incoming.deck);setIndex(incoming.index);setCard(incoming.card);setPhase(incoming.phase);setTurn(incoming.turn);setAliens(new Set(incoming.aliens));setUnits(incoming.units);setCursors(incoming.cursors);setSelected(incoming.selected);setMoved(incoming.moved);setLabMoved(incoming.labMoved);setReviveSpent(incoming.reviveSpent);setWeapon(incoming.weapon);setOver(incoming.over);setLevels(incoming.levels);setHands(incoming.hands);setLogs(incoming.logs);setPendingAttack(incoming.pendingAttack);setHistory(incoming.history||[]);setTimeout(()=>{applyingRemote.current=false},120)},[multiplayer?.view.revision,multiplayer?.view.gameState]);
 useEffect(()=>{if(!sendStateRef.current||applyingRemote.current)return;const timer=setTimeout(()=>sendStateRef.current?.({started,labCity,deck,index,card,phase,turn,aliens:[...aliens],units,cursors,selected,moved,labMoved,reviveSpent,weapon,over,levels,hands,logs,pendingAttack,history},active,!!over),80);return()=>clearTimeout(timer)},[started,labCity,deck,index,card,phase,turn,aliens,units,cursors,selected,moved,labMoved,reviveSpent,weapon,over,levels,hands,logs,pendingAttack,history,active]);
 const log=(m:string)=>setLogs(v=>[m,...v].slice(0,30));
 function remember(label:string){const positions=units.filter(u=>u.alive).map(u=>`${u.army[0]} C${u.city}-${u.tile}`).join(" · ")||"No surviving units";setHistory(v=>[{label,positions,state:{labCity,deck:deck.map(c=>({...c,resources:{...c.resources}})),index,card:card?{...card,resources:{...card.resources}}:null,phase,turn,aliens:[...aliens],units:units.map(u=>({...u})),cursors:{...cursors},selected,moved:{...moved},labMoved,reviveSpent,weapon,over,levels:{...levels},hands:{Light:{...hands.Light},Medium:{...hands.Medium},Heavy:{...hands.Heavy},Lab:{...hands.Lab}},logs:[...logs],pendingAttack:pendingAttack?{...pendingAttack,targets:[...pendingAttack.targets]}:null}},...v].slice(0,24))}
 function back(){if(!canAct)return;const moment=history[0];if(!moment)return;const s=moment.state;setLabCity(s.labCity);setDeck(s.deck);setIndex(s.index);setCard(s.card);setPhase(s.phase);setTurn(s.turn);setAliens(new Set(s.aliens));setUnits(s.units);setCursors(s.cursors);setSelected(s.selected);setMoved(s.moved);setLabMoved(s.labMoved);setReviveSpent(s.reviveSpent);setWeapon(s.weapon);setOver(s.over);setLevels(s.levels);setHands(s.hands);setLogs([`BACK: restored state before “${moment.label}”.`,...s.logs].slice(0,30));setPendingAttack(s.pendingAttack);setHistory(v=>v.slice(1))}
 function begin(){setDeck(makeDeck());setIndex(0);setCard(null);setPhase("draw");setTurn(0);setAliens(new Set());setUnits(initialUnits(labCity));setCursors({1:1,2:1,3:1,4:1,5:1});setSelected(null);setPendingAttack(null);setHistory([]);setMoved({});setLabMoved(false);setReviveSpent(0);setWeapon(0);setOver(null);setLevels({Light:0,Medium:0,Heavy:0,Lab:0});setHands({Light:empty(),Medium:empty(),Heavy:empty(),Lab:empty()});setLogs([`Lab command established outside City ${labCity}. Humans deploy from 15 downward; all alien counters begin at 1.`]);setStarted(true)}
 function protectedUnit(a:Army){return(a==="Heavy"&&levels.Heavy>=1)||(a==="Medium"&&levels.Heavy>=2)||(a==="Light"&&levels.Heavy>=3)}
 function overflowOrder(city:number){const from=CITY_RING.indexOf(city),home=CITY_RING.indexOf(labCity),clockwise=(home-from+5)%5,counter=(from-home+5)%5,step=clockwise<=counter?1:-1;return Array.from({length:4},(_,i)=>CITY_RING[(from+step*(i+1)+25)%5]).flatMap(target=>Array.from({length:15},(_,i)=>`${target}-${i+1}`))}
 function reinforcements(a:Set<string>,u:Unit[]){const wave:Army[]=["Heavy","Medium","Medium","Light","Light","Light"];let arrived=0;wave.forEach((army,i)=>{const occupied=new Set(u.filter(x=>x.alive).map(x=>`${x.city}-${x.tile}`));const tile=Array.from({length:15},(_,k)=>15-k).find(n=>!occupied.has(`${labCity}-${n}`)&&!a.has(`${labCity}-${n}`));if(tile){u.push({id:`${army}-R${index}-${i}`,army,city:labCity,tile,alive:true});arrived++}});log(`REINFORCEMENT EVENT: ${arrived}/6 units enter from 15 downward: Heavy, 2 Medium, then 3 Light at City ${labCity}.`)}
 function deploy(c:Card){const a=new Set(aliens),u=units.map(x=>({...x})),deployment=Math.max(0,c.aliens-levels.Medium),next=(n:number)=>n===15?1:n+1;let placed=0,overflowed=0,cursor=cursors[c.city];
  while(placed<deployment){let id="",probe=cursor;for(let checked=0;checked<15;checked++){const candidate=`${c.city}-${probe}`;if(!a.has(candidate)){id=candidate;cursor=next(probe);break}probe=next(probe)}if(!id){id=overflowOrder(c.city).find(candidate=>!a.has(candidate))||"";if(!id)break}let[city,tile]=id.split("-").map(Number),human=u.find(x=>x.alive&&x.city===city&&x.tile===tile);if(human){if(protectedUnit(human.army)){const local:string[]=[];let scan=cursor;for(let checked=0;checked<15;checked++){local.push(`${c.city}-${scan}`);scan=next(scan)}const redirected=[...local,...overflowOrder(c.city)].find(candidate=>!a.has(candidate)&&!u.some(x=>x.alive&&`${x.city}-${x.tile}`===candidate));if(redirected){log(`${human.army} armour deflects the dropping alien to ${redirected}.`);id=redirected;[city,tile]=id.split("-").map(Number);human=undefined;if(city===c.city)cursor=next(tile)}else{human.alive=false;log(`The board is full: a direct drop kills ${human.army}.`)}}else{human.alive=false;log(`${human.army} is killed by a direct drop.`)}}a.add(id);placed++;if(city!==c.city)overflowed++;
   const near=adj.get(id)||new Set();u.forEach(x=>{if(!x.alive||x.army==="Lab"||!near.has(`${x.city}-${x.tile}`))return;const count=[...(adj.get(`${x.city}-${x.tile}`)||[])].filter(k=>a.has(k)).length;if(count>=KILLS[x.army]){x.alive=false;log(`${x.army} is overwhelmed at City ${x.city}–${x.tile}.`)}});
  }
  if(overflowed)log(`HIVE OVERFLOW: ${overflowed} alien${overflowed===1?"":"s"} spread out of City ${c.city}.`);
  log(`City ${c.city} alien counter: ${cursor} next (counting up).`);
  if(c.reinforcement)reinforcements(a,u);setCursors(v=>({...v,[c.city]:cursor}));setAliens(a);setUnits(u)
 }
 function draw(){if(!canAct)return;if(index>=deck.length){remember("Mothership arrival");setOver("The Mothership arrives. Humanity loses.");return}const c=deck[index],deployment=Math.max(0,c.aliens-levels.Medium);remember(`Draw invasion card ${index+1}: City ${c.city}`);setCard(c);setIndex(index+1);deploy(c);setPhase("collect");log(`${c.aliens}${levels.Medium?` − ${levels.Medium}`:""} = ${deployment} aliens deploy to City ${c.city}.`)}
 function collect(){if(!canAct||!card)return;remember(`${active} collected card resources`);setHands(h=>{const next={...h,[active]:{...h[active]}};Object.entries(card.resources).forEach(([r,n])=>next[active][r as Resource]+=n||0);return next});setPhase("actions");log(`${active} collects resources.`)}
 function canCommand(unit:Unit){return unit.army===active||(active==="Light"&&((unit.army==="Medium"&&levels.Light>=2)||(unit.army==="Heavy"&&levels.Light>=3)))}
 function movementPath(start:string,target:string,max:number){const queue:Array<[string,string[]]>=[[start,[]]],seen=new Set([start]);while(queue.length){const[current,path]=queue.shift()!;for(const next of adj.get(current)||[]){if(seen.has(next)||aliens.has(next))continue;const nextPath=[...path,next];if(next===target)return nextPath;seen.add(next);if(nextPath.length<max)queue.push([next,nextPath])}}return null}
 function move(cell:Cell){if(!canAct||phase!=="actions"||!selected||pendingAttack)return;const unit=units.find(x=>x.id===selected&&x.alive),spent=selected?moved[selected]||0:0;if(!unit||!canCommand(unit)||spent>=MOVE[unit.army]||aliens.has(cell.id)||units.some(x=>x.alive&&x.id!==unit.id&&x.city===cell.city&&x.tile===cell.number))return;const remaining=MOVE[unit.army]-spent,path=movementPath(`${unit.city}-${unit.tile}`,cell.id,remaining);if(!path){log("No open route within the unit’s remaining movement.");return}remember(`${unit.army} moved from C${unit.city}-${unit.tile} toward C${cell.city}-${cell.number}`);const a=new Set(aliens);let defeated=0;for(let i=0;i<path.length;i++){const step=path[i],targets=[...(adj.get(step)||[])].filter(id=>a.has(id)),used=spent+i+1;if(targets.length>KILLS[unit.army]){const[city,tile]=step.split("-").map(Number);setAliens(a);setUnits(v=>v.map(x=>x.id===unit.id?{...x,city,tile}:x));setMoved(v=>({...v,[unit.id]:used}));setPendingAttack({unitId:unit.id,targets,remaining:KILLS[unit.army]});log(`${unit.army} has ${targets.length} adjacent aliens. Choose ${KILLS[unit.army]} targets.`);return}targets.forEach(id=>{a.delete(id);defeated++})}const used=spent+path.length;setAliens(a);setUnits(v=>v.map(x=>x.id===unit.id?{...x,city:cell.city,tile:cell.number}:x));setMoved(v=>({...v,[unit.id]:used}));if(used>=MOVE[unit.army])setSelected(null);log(`${active} command moves ${unit.army} ${path.length} step${path.length===1?"":"s"}, passes friendly units, kills ${defeated}, and has ${MOVE[unit.army]-used} movement remaining.`)}
 function chooseAlien(id:string){if(!canAct||!pendingAttack||!pendingAttack.targets.includes(id)||!aliens.has(id))return;remember(`Selected alien target ${id}`);setAliens(v=>{const next=new Set(v);next.delete(id);return next});const remaining=pendingAttack.remaining-1;if(remaining>0){setPendingAttack({...pendingAttack,targets:pendingAttack.targets.filter(target=>target!==id),remaining});log(`Target selected. Choose ${remaining} more.`);return}const unit=units.find(x=>x.id===pendingAttack.unitId);setPendingAttack(null);if(unit&&(moved[unit.id]||0)>=MOVE[unit.army])setSelected(null);log("Target selection complete. Movement may continue if available.")}
 function upgrade(army:Army){if(!canAct)return;const l=levels[army];if(l>=3)return;const c=COSTS[army][l],h=hands[army];if(Object.entries(c).some(([r,n])=>h[r as Resource]<(n||0))){log("Not enough resources for that upgrade.");return}remember(`${army} upgraded to Level ${l+1}`);setHands(all=>{const next={...all[army]};Object.entries(c).forEach(([r,n])=>next[r as Resource]-=n||0);return{...all,[army]:next}});setLevels(v=>({...v,[army]:l+1}));log(`${army} reaches Level ${l+1}.`)}
 function commit(){if(!canAct||hands[active]["Alien Tech"]<1||weapon>=15)return;remember(`${active} committed Alien Tech`);setHands(v=>({...v,[active]:{...v[active],"Alien Tech":v[active]["Alien Tech"]-1}}));const n=weapon+1;setWeapon(n);if(n===15)setOver("The Ultimate Weapon is complete. Humanity wins!")}
 function manufacture(){if(!canAct)return;const l=levels[active];if(l<2)return;const each=l===2?3:2,h={...hands[active]};if(h.Steel<each||h.Energy<each||h.Intelligence<each){log(`Alien Tech requires ${each} Steel, ${each} Energy and ${each} Intelligence.`);return}remember(`${active} manufactured Alien Tech`);h.Steel-=each;h.Energy-=each;h.Intelligence-=each;h["Alien Tech"]++;setHands(v=>({...v,[active]:h}));log(`${active} manufactures Alien Tech using ${each} Steel, ${each} Energy and ${each} Intelligence.`)}
 function share(r:Resource,target:Army){if(!canAct||hands[active][r]<1)return;remember(`${active} shared ${r} with ${target}`);setHands(v=>({...v,[active]:{...v[active],[r]:v[active][r]-1},[target]:{...v[target],[r]:v[target][r]+1}}))}
 function revive(id:string){if(!canAct)return;const unit=units.find(x=>x.id===id&&!x.alive);if(active!=="Lab"||phase!=="actions"||!unit||unit.army==="Lab")return;const capacity=[0,2,4,6][levels.Lab],cost={Light:1,Medium:2,Heavy:3,Lab:99}[unit.army];if(reviveSpent+cost>capacity){log("Not enough revival capacity remaining this turn.");return}const occupied=new Set(units.filter(x=>x.alive).map(x=>`${x.city}-${x.tile}`)),tile=Array.from({length:15},(_,i)=>15-i).find(n=>!occupied.has(`${labCity}-${n}`)&&!aliens.has(`${labCity}-${n}`));if(!tile){log(`No safe arrival space is available in City ${labCity}.`);return}remember(`Revived ${unit.army} at C${labCity}-${tile}`);setUnits(v=>v.map(x=>x.id===id?{...x,alive:true,city:labCity,tile}:x));setReviveSpent(v=>v+cost);log(`${unit.army} unit revived at City ${labCity}–${tile} for ${cost} point${cost===1?"":"s"}.`)}
 function relocateLab(target:number){if(!canAct)return;const order=[1,2,3,5,4],at=order.indexOf(labCity),neighbours=[order[(at+4)%5],order[(at+1)%5]];if(active!=="Light"||phase!=="actions"||levels.Light<1||labMoved||!neighbours.includes(target))return;if(Array.from({length:15},(_,i)=>`${target}-${i+1}`).every(id=>aliens.has(id))){log(`City ${target} has already fallen.`);return}remember(`Moved Lab from City ${labCity} to City ${target}`);setLabCity(target);setLabMoved(true);log(`Light command evacuates the Lab to City ${target}. Alien counters are unchanged.`)}
 function end(){if(!canAct)return;if(pendingAttack){log(`Choose ${pendingAttack.remaining} remaining alien target${pendingAttack.remaining===1?"":"s"} before ending the turn.`);return}remember(`Ended ${active} turn`);if(Array.from({length:15},(_,i)=>`${labCity}-${i+1}`).every(id=>aliens.has(id))){setOver(`City ${labCity} is still fully occupied at the end of the turn. The Lab is destroyed and humanity loses.`);return}setTurn((turn+1)%4);setPhase("draw");setCard(null);setMoved({});setLabMoved(false);setReviveSpent(0);setSelected(null)}
 const chosen=units.find(x=>x.id===selected);
 return <main className="shell">
  {multiplayer&&<div className="room-bar"><b>ROOM {multiplayer.code}</b><span>{canAct?`Your ${active} command turn`:`Waiting for ${active} command`}</span><small>You control {multiplayer.armies.join(", ")}</small></div>}
  <header><div><p className="eyebrow">COOPERATIVE TACTICAL PROTOTYPE</p><h1>Alien Invasion</h1></div><div className="weapon"><span>ULTIMATE WEAPON <b>{weapon}/15</b></span><div>{Array.from({length:15},(_,i)=><i key={i} className={i<weapon?"on":""}/>)}</div></div></header>
  {!started?<section className="setup"><div><p className="eyebrow">ESTABLISH THE LAB</p><h2>Choose the landing city</h2><p>The Lab sits outside its city. Humans deploy from space 15 downward: Heavy on 15, Medium on 14–13, and Light on 12–10. All aliens deploy upward from 1 to 15. The Lab is destroyed only if all 15 city spaces remain occupied when a player ends their turn.</p><nav>{[1,2,3,4,5].map(c=><button key={c} className={labCity===c?"picked":""} style={{"--city":COLORS[c-1]} as React.CSSProperties} onClick={()=>setLabCity(c)}>City {c}</button>)}</nav><button className="primary" onClick={begin}>Begin invasion</button></div><aside><b>15</b><span>ALIEN TECH<br/>TO WIN</span></aside></section>:
  <><section className="status"><div><span>ACTIVE ARMY</span><b>{active}</b></div><div><span>PHASE</span><b>{phase}</b></div><div><span>DECK</span><b>{60-index} cards</b></div><div><span>ALIENS</span><b>{aliens.size}</b></div></section>
  {over&&<div className="over"><b>{over}</b><button onClick={()=>setStarted(false)}>New game</button></div>}
  <div className="game"><section className="map-panel"><div className="map-title"><div><p className="eyebrow">THE FIVE MUNICIPALITIES</p><h2>Battle map</h2></div><p>{pendingAttack?`Choose ${pendingAttack.remaining} highlighted alien target${pendingAttack.remaining===1?"":"s"}.`:chosen?`${chosen.army} selected · ${MOVE[chosen.army]-(moved[chosen.id]||0)} movement remaining`:"Select a meeple, then an empty destination. Friendly units may be passed."}</p></div>
   <svg className="map" viewBox="-60 -70 1260 1010">{board.map(c=>{const invader=aliens.has(c.id),target=pendingAttack?.targets.includes(c.id),here=units.filter(u=>u.alive&&u.city===c.city&&u.tile===c.number);return <g key={c.id} className={target?"target-cell":""} onClick={()=>target?chooseAlien(c.id):move(c)}><polygon points={c.points.map(p=>p.join(",")).join(" ")} fill={COLORS[c.city-1]}/><text className="num" x={c.center[0]} y={c.center[1]-14}>{c.number}</text>{invader&&<g className={`alien ${target?"target":""}`} transform={`translate(${c.center[0]} ${c.center[1]+10})`}><circle r="17"/><path d="M-8 2L-15 14M8 2L15 14M-8-2L-14-13M8-2L14-13"/><circle cx="-5" cy="-2" r="2"/><circle cx="5" cy="-2" r="2"/></g>}{here.map((u,i)=><g key={u.id} className={`unit ${u.army.toLowerCase()} ${selected===u.id?"selected":""}`} transform={`translate(${c.center[0]+i*7} ${c.center[1]+11})`} onClick={e=>{e.stopPropagation();if(!pendingAttack&&canAct&&phase==="actions"&&canCommand(u))setSelected(u.id)}}><circle r="16"/><text y="5">{u.army[0]}</text></g>)}</g>})}{LAYOUTS.map((l,i)=>{const city=i+1,y=l.r?l.y+535:-24,occupied=Array.from({length:15},(_,n)=>aliens.has(`${city}-${n+1}`)).filter(Boolean).length;return <g key={city}><text className="city-label" x={l.x+195} y={y}>CITY {city} · {occupied}/15</text>{labCity===city&&<g className="lab-command" transform={`translate(${l.x+195} ${y+(l.r?34:-34)})`}><rect x="-42" y="-14" width="84" height="28" rx="4"/><text y="5">LAB COMMAND</text></g>}</g>})}</svg>
  </section><aside className="rail"><section className="deck"><span className="count">{60-index}</span>{card?<div className="card" style={{"--city":COLORS[card.city-1]} as React.CSSProperties}><small>INVASION CARD</small><h3>City {card.city}</h3><div className="drop"><b>{card.aliens}</b>{levels.Medium>0&&<strong>− {levels.Medium}</strong>}<span>ALIENS<br/>DEPLOY<br/><small>= {Math.max(0,card.aliens-levels.Medium)} LAND</small></span></div><div className="rewards">{Object.entries(card.resources).map(([r,n])=><span key={r}><b>{n}</b>{r}</span>)}</div>{card.reinforcement&&<em>REINFORCEMENTS · 3L 2M 1H</em>}</div>:<div className="card back"><b>INVASION</b><small>THE MOTHERSHIP IS COMING</small></div>}{phase==="draw"?<button className="primary" onClick={draw}>Draw card</button>:phase==="collect"?<button className="primary" onClick={collect}>Collect resources</button>:<button className="primary" onClick={end}>End {active} turn</button>}</section><section className="history"><header><h4>ACTION HISTORY</h4><button disabled={!history.length} onClick={back}>← Back one action</button></header>{history.length?history.map((moment,i)=><div key={`${moment.label}-${i}`}><b>{moment.label}</b><small>{moment.positions}</small></div>):<p>No actions recorded yet.</p>}</section><section className="log"><h4>EVENT LOG</h4>{logs.map((x,i)=><p key={i}>{x}</p>)}</section></aside></div>
  <section className="players">{ARMIES.map(a=><article key={a} className={active===a?"active":""}><div className="player-head"><i className={a.toLowerCase()}>{a==="Lab"?"LAB":a[0]}</i><div><span>{a.toUpperCase()} COMMAND</span><b>Level {levels[a]}</b></div></div><div className="hand">{RESOURCES.map(r=><div key={r}><span>{r}</span><b>{!multiplayer||multiplayer.armies.includes(a)?hands[a][r]:"PRIVATE"}</b></div>)}</div><div className="tree">{POWERS[a].map((p,i)=><button key={p} className={levels[a]>i?"done":levels[a]===i&&active===a&&phase==="actions"?"ready":""} onClick={()=>active===a&&phase==="actions"&&upgrade(a)}><span>L{i+1}</span><b>{p}</b><small>{costText(COSTS[a][i])}</small></button>)}</div>{canAct&&active===a&&phase==="actions"&&<div className="actions"><button onClick={commit}>Commit Tech</button><button disabled={levels[a]<2} onClick={manufacture}>Manufacture</button>{a==="Light"&&levels.Light>=1&&<div className="relocate"><span>Move Lab from City {labCity}</span>{[1,2,3,4,5].filter(c=>{const order=[1,2,3,5,4],at=order.indexOf(labCity);return [order[(at+4)%5],order[(at+1)%5]].includes(c)}).map(c=><button key={c} disabled={labMoved} onClick={()=>relocateLab(c)}>City {c}</button>)}</div>}{a==="Lab"&&levels.Lab>=1&&<div className="revive"><span>Revive capacity: {[0,2,4,6][levels.Lab]-reviveSpent} remaining</span>{units.filter(u=>!u.alive&&u.army!=="Lab").map(u=>{const cost={Light:1,Medium:2,Heavy:3,Lab:99}[u.army];return <button key={u.id} disabled={cost>[0,2,4,6][levels.Lab]-reviveSpent} onClick={()=>revive(u.id)}>Revive {u.army} · {cost}</button>})}{!units.some(u=>!u.alive&&u.army!=="Lab")&&<small>No fallen units</small>}</div>}<details><summary>Share 1</summary>{ARMIES.filter(t=>t!==a).map(t=><div key={t}><span>{t}</span>{RESOURCES.map(r=><button key={r} onClick={()=>share(r,t)}>{r[0]}</button>)}</div>)}</details></div>}</article>)}</section></>}
 </main>
}
